### ISSUE TITLE
./waf uninstall keeps failing

### ISSUE THREAD

**Issue by rhetr** [original-male/non#162]
i can't get ./waf uninstall to work, i keep getting this error:

    Build failed
    Traceback (most recent call last):
      File "/media/Data/code/non/.waf-1.8.0-f4f5e7c10cf1681215dc56fc3b992944/waflib/Task.py", line 103, in process
        ret=self.run()
      File "/media/Data/code/non/.waf-1.8.0-f4f5e7c10cf1681215dc56fc3b992944/waflib/Build.py", line 456, in run 
        return self.generator.exec_task()
      File "/media/Data/code/non/.waf-1.8.0-f4f5e7c10cf1681215dc56fc3b992944/waflib/Build.py", line 481, in exec_symlink_as
        self.generator.bld.do_link(src,destfile,tsk=self)
    TypeError: do_link() got an unexpected keyword argument 'tsk'

**Comment by nico202** [comment]
Edit the file: /media/Data/code/non/.waf-1.8.0-f4f5e7c10cf1681215dc56fc3b992944/waflib/Build.py, line 481:
replace
`self.generator.bld.do_link(src,destfile,tsk=self)`

with 
`                self.generator.bld.do_link(src,destfile)`

then sudo ./waf uninstall will works
