### ISSUE TITLE
Non-sequencer and others won build, Liblo and Jack_get_property missing

### ISSUE THREAD

**Issue by arpeggio1234** [original-male/non#196]
Hello, i am trying to build and install this great project and get some building problems,
i am new to building things and installing in Linux, i use Linux mint 17.3 and sometimes i get the clue
of doing things(i program and read a lot) but this one is to big for me, or is it just as simple as 
Installing Liblo and the jack_get_property thing, and then i am done, ready for building.
On the Arch-linux site for non i saw more dependencies for non, so just need a little help.
Which ones to install to get me running, 
Thanks in advance, dian from the Netherlands,  and the non daw, all four, looks great.
And by the way is Linux mint okay for music midi sequencing or better use Ubuntu or better use Arch-Linux.

Here is the log file, 

# project non-things (xxx) configured on Wed Jun 29 16:38:14 2016 by
# waf 1.8.0 (abi 98, python 20706f0 on linux2)
# using ./waf configure
#
----------------------------------------
Setting top to
/home/dian/non
----------------------------------------
Setting out to
/home/dian/non/build
----------------------------------------
Checking for 'gcc' (C compiler)
find program=['gcc', 'cc'] paths=['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin', '/usr/games', '/usr/local/games'] var='CC' -> ['/usr/bin/gcc']
find program=['ar'] paths=['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin', '/usr/games', '/usr/local/games'] var='AR' -> ['/usr/bin/ar']
/usr/bin/gcc
----------------------------------------
Checking for 'g++' (C++ compiler)
find program=['g++', 'c++'] paths=['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin', '/usr/games', '/usr/local/games'] var='CXX' -> ['/usr/bin/g++']
(tool ar is already loaded, skipping)
/usr/bin/g++
----------------------------------------------------
Checking for program 'pkg-config'
['/usr/bin/pkg-config']
find program=['pkg-config'] paths=['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin', '/usr/games', '/usr/local/games'] var='PKGCONFIG' -> ['/usr/bin/pkg-config']
----------------------------------------------------
Checking for 'ntk' >= 1.3.0
['/usr/bin/pkg-config', '--atleast-version=1.3.0', 'ntk']
['/usr/bin/pkg-config', '--cflags', '--libs', 'ntk']
out: -pthread -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/local/include/ntk -I/usr/include/cairo -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng12  -L/usr/local/lib -lntk -lcairo  

yes
----------------------------------------------------
Checking for 'ntk_images' >= 1.3.0
['/usr/bin/pkg-config', '--atleast-version=1.3.0', 'ntk_images']
['/usr/bin/pkg-config', '--cflags', '--libs', 'ntk_images']
out: -pthread -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/local/include/ntk -I/usr/include/cairo -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng12  -L/usr/local/lib -lntk_images -lntk -lcairo  

yes
----------------------------------------------------
Checking for program 'ntk-fluid'
['/usr/local/bin/ntk-fluid']
find program=['ntk-fluid'] paths=['/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin', '/usr/games', '/usr/local/games'] var='NTK_FLUID' -> ['/usr/local/bin/ntk-fluid']
----------------------------------------------------
Checking for 'jack' >= 0.103.0
['/usr/bin/pkg-config', '--atleast-version=0.103.0', 'jack']
['/usr/bin/pkg-config', '--cflags', '--libs', 'jack']
out:  -ljack  

yes
----------------------------------------------------
Checking for jack_port_get_latency_range()
==>
#include <jack/jack.h>
int main (int argc, char**argv) { jack_port_get_latency_range( (jack_port_t*)0, JackCaptureLatency, (jack_latency_range_t *)0 ); }
<==
[1/2] [32mc: build/.conf_check_038855f1ca7c69df0d7c1ea0925b3c02/test.c -> build/.conf_check_038855f1ca7c69df0d7c1ea0925b3c02/testbuild/test.c.1.o
[0m
['/usr/bin/gcc', '-MD', '-DHAVE_NTK=1', '-DHAVE_NTK_IMAGES=1', '-DHAVE_JACK=1', '../test.c', '-c', '-o', '/home/dian/non/build/.conf_check_038855f1ca7c69df0d7c1ea0925b3c02/testbuild/test.c.1.o']
[2/2] [33mcprogram: build/.conf_check_038855f1ca7c69df0d7c1ea0925b3c02/testbuild/test.c.1.o -> build/.conf_check_038855f1ca7c69df0d7c1ea0925b3c02/testbuild/testprog
[0m
['/usr/bin/gcc', 'test.c.1.o', '-o', '/home/dian/non/build/.conf_check_038855f1ca7c69df0d7c1ea0925b3c02/testbuild/testprog', '-Wl,-Bstatic', '-Wl,-Bdynamic']
yes
----------------------------------------------------
Checking for function jack_get_property
==>
#include <jack/metadata.h>

int main(int argc, char **argv) {
	void *p;
	(void)argc; (void)argv;
	p=(void*)(jack_get_property);
	return 0;
}

<==
[1/2] [32mcxx: build/.conf_check_038b537f455f0039a4f90cf649d60302/test.cpp -> build/.conf_check_038b537f455f0039a4f90cf649d60302/testbuild/test.cpp.1.o
[0m
['/usr/bin/g++', '-MD', '-DHAVE_NTK=1', '-DHAVE_NTK_IMAGES=1', '-DHAVE_JACK=1', '-DHAVE_JACK_PORT_GET_LATENCY_RANGE=1', '../test.cpp', '-c', '-o', '/home/dian/non/build/.conf_check_038b537f455f0039a4f90cf649d60302/testbuild/test.cpp.1.o']
err: ../test.cpp:1:27: fatal error: jack/metadata.h: No such file or directory
 #include <jack/metadata.h>
                           ^
compilation terminated.

from /home/dian/non: Test does not build: Traceback (most recent call last):
  File "/home/dian/non/.waf-1.8.0-f4f5e7c10cf1681215dc56fc3b992944/waflib/Tools/c_config.py", line 478, in run_c_code
    bld.compile()
  File "/home/dian/non/.waf-1.8.0-f4f5e7c10cf1681215dc56fc3b992944/waflib/Build.py", line 182, in compile
    raise Errors.BuildError(self.producer.error)
BuildError: Build failed
 -> task in 'testprog' failed (exit status 1): 
	{task 140177592640592: cxx test.cpp -> test.cpp.1.o}
['/usr/bin/g++', '-MD', '-DHAVE_NTK=1', '-DHAVE_NTK_IMAGES=1', '-DHAVE_JACK=1', '-DHAVE_JACK_PORT_GET_LATENCY_RANGE=1', '../test.cpp', '-c', '-o', '/home/dian/non/build/.conf_check_038b537f455f0039a4f90cf649d60302/testbuild/test.cpp.1.o']

not found
from /home/dian/non: The configuration failed
----------------------------------------------------
Checking for 'x11'
['/usr/bin/pkg-config', '--cflags', '--libs', 'x11']
out:  -lX11  

yes
----------------------------------------------------
Checking for 'liblo' >= 0.26
['/usr/bin/pkg-config', '--atleast-version=0.26', 'liblo']
not found
from /home/dian/non: The configuration failed

**Comment by egasimus** [comment]
Hi @arpeggio1234! I'm not the author of this project but I thought I'd give you a few pointers. Everyone, please correct me if I happen to be wrong, this is all off the top of my head.

If memory serves, on Mint, Ubuntu, or Debian, the packages that you need to install are be named `lib*-dev`; e.g. `liblo-dev` and `libjack-dev` (or `libjack2-dev`).

I wouldn't recommend Mint, or Manjaro for that matter, as your daily driver -- both are user-friendly remixes of more mainstream distros (at least in Manjaro's case, with the status of a fork -- i.e. you're not benefitting from any improvements to Arch which is what Manjaro is based on). Both are understaffed as compared to their upstream counterparts, and both have had critical security issues over recent months that haven't been dealt with in a particularly professional manner.

This is why I'd recommend either Debian, Ubuntu, or possibly KXStudio; as well as Arch or Antergos (Antergos being 100% Arch + a graphical installer and extra eyecandy). On the Arch family of distros you have the AUR, which is a repository of user-contributed build scripts. Once you have an AUR helper in place, e.g. Yaourt, building latest Non from source is as easy as `yaourt -S non-daw-git`; dependencies are handled automatically. Also, when you install JACK or Liblo you would automatically get all you need to build stuff against them -- Arch doesn't have those files in separate `-dev` packages.

**Comment by egasimus** [comment]
In any case, your choice of distro per se does not have much influence on how easy it is to make music, aside from which packages are made readily available (e.g. KXStudio comes with Non in its repositories -- though I don't know if it isn't an outdated version!).

It is much more important to have a realtime or low-latency kernel; otherwise you might not be able to get low latency without pops and clicks. This is again something you can build and use on any system, although it's not equally difficult everywhere. I know that Ubuntu used to offer a pre-built lowlatency kernel in its repos; while getting the latest RT kernel on Arch is as easy as typing `yaourt -S linux-rt`, confirming a few prompts, then just waiting for it to compile.

It is also important to have a recent enough kernel that includes support for the hardware that you're using. Generally, the newer kernel you have, the more likely is it for your hardware to be supported. "Bleeding edge" distros such as Arch offer new package versions constantly (including kernels), while versioned distros stick with older but (theoretically) more stable versions of stuff for long periods of time, forcing you to add custom package repos (e.g. PPAs, on Debianish systems) and/or build things yourself to get the latest and greatest..

Hope those pointers have been helpful. Have fun!

**Comment by arpeggio1234** [comment]
Thanks, i will go for Arch, and try to get the libs-devs and settle it in mint and then 
go for Arch,
Do you happen to know a good way, site, ebook for getting familiar to linux,
it's so much, so hugh, i don't know where to start.
By familiar i mean knowing about installing, configuring linux, and repositories and other linux related words to know. Especialy for audio and midi and music, Thanks, Dian

**Comment by egasimus** [comment]
http://wiki.archlinux.org/ is a very comprehensive and starter-friendly resource. Of course, many things in it are Arch-specific, but many others aren't. :) When reentering Linux a couple years ago I successfully maintained a very stripped down Ubuntu installation with it as my main resource.

I can recommend no other source of info for beginners since I haven't used one but you've got the whole Internet. Look up how ALSA, JACK, PulseAudio work I guess.

Keep this thread updated when you have new build results, friend :) I wouldn't like to drive the conversation off topic for too long, I know how some people don't like that. It would be interesting to see if properly setup builds still fail in a particular way on your system though; as the old saying goes, edge cases lurk in every corner. No wait I just made that up.

P.S. An easy way to experiment with different distros is boot their live environments in a virtual machine, like VirtualBox by the way.

**Comment by Frantik02** [comment]
Hello, I am having a similar problem. I use Lubuntu 16.04, and of course non(e) of the required packages are including. So far I've been successful installing the packages, but I seem to have an issue. I've followed the instructions in the readme.build step by step, but when trying to build ntk by using ./waf configure, I get the following output
nico@nico:~/non$ cd lib/ntk
nico@nico:~/non/lib/ntk$ ./waf configure
Setting top to                           : /home/nico/non/lib/ntk 
Setting out to                           : /home/nico/non/lib/ntk/build 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking for program 'pkg-config'                    : ['/usr/bin/pkg-config'] 
Checking for 'x11'                                   : not found 
The configuration failed
(complete log in /home/nico/non/lib/ntk/build/config.log)

For some reason, x11 (which I actually don't know what that is, I'm just a musician/producer looking forward to trying a new piece of software) seems to not be installed. Where do I get x11?

Also, if I backtrack and try to execute ./waf configure in /non$, I get the following output

nico@nico:~$ cd /home/nico/non lib/ntk
nico@nico:~/non$ ./waf configure
Setting top to                           : /home/nico/non 
Setting out to                           : /home/nico/non/build 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking for program 'pkg-config'                    : ['/usr/bin/pkg-config'] 
Checking for 'ntk' >= 1.3.0                          : not found 
The configuration failed
(complete log in /home/nico/non/build/config.log)

I think that last one is an unnecesary step, as the readme.build file indicates that ./waf configure should be executed in ~/non/lib/ntk and not just ~/non/. Therefore I believe that my problem is exclusively related to the x11 issue described earlier. I hope I am not doing something really stupid and I will thank you in advance for your help and all the knowledge any of you may bestow upon me. 

Regards,

nico

**Comment by nico202** [comment]
Hi, X11 is the linux [ "window system"](https://en.wikipedia.org/wiki/X_Window_System)

To compile programs that uses x11 libraries, on [xl]ubuntu you need to install the development pack.
I'm not running ubuntu but if I'm not wrong it's called libx11-dev, and you can install it via:
`sudo apt-get install libx11-dev`

Let me know

**Comment by Frantik02** [comment]
Hey man, many, many, many, maaany thanks. And I know I should open another issue, but in my ignorance and desperation I found this issue to be similar to mine. I will inform you of my progress here.

I installed libx11-dev and ./waf configure detected it at last, but the next thing required, which is fontconfig, seems to be missing. I tried to install fontconfig, and the terminal output was, to my surprise, that fontconfig is already installed, but ./waf configure is not detecting it. :sob: 

nico@nico:~/non$ cd lib/ntk
nico@nico:~/non/lib/ntk$ ./waf configure
Setting top to                           : /home/nico/non/lib/ntk 
Setting out to                           : /home/nico/non/lib/ntk/build 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking for program 'pkg-config'                    : ['/usr/bin/pkg-config'] 
Checking for 'x11'                                   : yes 
Checking for 'fontconfig'                            : not found 
The configuration failed
(complete log in /home/nico/non/lib/ntk/build/config.log)
nico@nico:~/non/lib/ntk$ 

I hope you can still help me, and I promise I will open a new issue. Thank you very much in advance.

**Comment by nico202** [comment]
Still not sure, but what about ```libfontconfig1-dev```?

**Comment by arpeggio1234** [comment]
Hello Frantik02, i let go off the non-seq in linux-mint, i let go of linux mint at all for now.
So for working this out in your system i leave it to nico202, because i can not help, i needed help for this. What i will say to you for now is, i am using KX-studio and the non-sequencer was already installed there, and was working without one problem, that is the good news.
Dian

**Comment by Frantik02** [comment]
Hey guys, sorry for the late reply. I appreciate the gesture, dear arpeggio1234. And I think I'm getting closer to success. Turns out lobfontconfig1-dev worked and the next step was to install Cairo, which I did. When the time to ./waf configure came, the output was the following (please take note of the bold output line):

nico@nico:~/non/lib/ntk$ ./waf configure
Setting top to                           : /home/nico/non/lib/ntk 
Setting out to                           : /home/nico/non/lib/ntk/build 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking for program 'pkg-config'                    : ['/usr/bin/pkg-config'] 
Checking for 'x11'                                   : yes 
Checking for 'fontconfig'                            : yes 
Checking for 'xft'                                   : yes 
Checking for 'cairo' >= 1.10.0                       : yes 
Checking for header unistd.h                         : yes 
Checking for header pthread.h                        : yes 
Checking for header dirent.h                         : yes 
Checking for header string.h                         : yes 
Checking for header locale.h                         : yes 
Checking for header sys/select.h                     : yes 
Checking for header dlfcn.h                          : yes 
**Checking for header sys/stdtypes.h                   : not found** 
Checking for header pthread.h                        : yes 
Checking for header png.h                            : yes 
Checking for PTHREAD_MUTEX_RECURSIVE                 : yes 
Checking for function strtoll                        : yes 
Checking for function scandir                        : yes 
Checking for library jpeg                            : yes 
Checking for 'libpng'                                : yes 
Checking for 'zlib'                                  : yes 
Checking for long long type                          : yes 
Checking for function strcasecmp                     : yes 
Checking for function snprintf                       : yes 
Checking for function vsnprintf                      : yes 
Checking sizeof short                                : yes 
Checking sizeof int                                  : yes 
Checking sizeof long                                 : yes 
---
Note: "not found" is OK for optional items.
---
Building for performance

'configure' finished successfully (4.473s)

Apparently, it is safe to continue with the process, and as the terminal tells me, sys/stdtypes.h is not necessary. However, I'm concerned about the stability of non. What if sys/stdtypes.h is actually necessary?

I am not asking for any more guidance from you, as now I will proceed to build non. If anything terrible happens, I will be sure to create a new issue as I should have before. Cheers and thank you very much for all the help.

Regards,

nico.
